#!/bin/bash
# vim: set ts=4 sw=4 et:

source $XBPS_SHUTILSDIR/common.sh

read_pkg ignore-problems
for sub_name in $subpackages; do
    if [ $sub_name = $XBPS_TARGET_PKG ]; then
        ${sub_name}_package
    fi
done
printf "archs: %s\n\n" "$archs"
printf "bootstrap: %s\n\n" "$bootstrap"
printf "broken: %s\n\n" "$broken"
printf "depends: %s\n\n" "$depends"
printf "hostmakedepends: %s\n\n" "$hostmakedepends"
printf "makedepends: %s\n\n" "$makedepends"
printf "nocross: %s\n\n" "$nocross"
printf "pkgname: %s\n\n" "$pkgname"
printf "restricted: %s\n\n" "$restricted"
printf "revision: %s\n\n" "$revision"
printf "subpackages: %s\n\n" "$subpackages"
printf "version: %s\n\n" "$version"
printf "provides: %s\n\n" "$provides"
printf "lib32disabled: %s\n\n" "$lib32disabled"
printf "nodebug: %s\n\n" "$nodebug"
