#!/bin/bash
# vim: set ts=4 sw=4 et:

source $XBPS_SHUTILSDIR/common.sh

read_pkg ignore-problems
for sub_name in $subpackages; do
    if [ $sub_name = $XBPS_TARGET_PKG ]; then
        ${sub_name}_package
    fi
done
while IFS= read -r pkg_var; do
        print_var=
        case "${pkg_var}" in
            archs) print_var="$archs ";;
            bootstrap) print_var="$bootstrap ";;
            broken) print_var="$broken ";;
            depends) print_var="$depends ";;
            hostmakedepends) print_var="$hostmakedepends ";;
            makedepends) print_var="$makedepends ";;
            nocross) print_var="$nocross ";;
            pkgname) print_var="$pkgname ";;
            restricted) print_var="$restricted ";;
            revision) print_var="$revision ";;
            subpackages) print_var="$subpackages ";;
            version) print_var="$version ";;
            provides) print_var="$provides ";;
            lib32disabled) print_var="$lib32disabled ";;
            nodebug) print_var="$nodebug ";;
        esac # the space at the end of each is essential for unset vars
        if [ -n "$print_var" ]; then
                printf "%s\n" "$(printf "${print_var% }" | tr -t '\n\r' ' ')"
        fi # The trailing space gets stripped before printing anyway
done
